# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MonitoringNetworks
                                 A QGIS plugin
 Optimize the selection of monitoring wells to maximize information and mininize costs

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-14
        copyright            : (C) 2026 by Lorena Gonzalez
        email                : lorenagzp@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MonitoringNetworks class from file MonitoringNetworks.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """

    from .monitoring_networks_core import MonitoringNetworks
    return MonitoringNetworks(iface)
