# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MonitoringNetworksDialog
                                 A QGIS plugin
 Optimize the selection of monitoring wells to maximize information and mininize costs
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-14
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Lorena Gonzalez
        email                : lorenagzp@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from PyQt5.QtWidgets import QAction
from PyQt5.QtGui import QIcon
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.core import QgsMessageLog


class MonitoringNetworks:
    def __init__(self, iface):
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        self.dlg = None
        self.actions = []
        self.menu = "&MonitoringNetworks"
        self.toolbar = self.iface.addToolBar("MonitoringNetworks")

        # Regarding the translation
        plugin_dir = os.path.dirname(__file__)
        locale = QSettings().value("locale/userLocale","en")[0:2]
        localePath = os.path.join(
            plugin_dir, 'i18n', f'monitoring_networks_{locale}.qm'
        ) #Path to search the translation, based on the QGIS/system language
        QgsMessageLog.logMessage("Locale path: " + localePath, "Loading Pugin") #Message to user

        if os.path.exists(localePath):
            QgsMessageLog.logMessage("Translation found for: " + localePath) #Message to user
            self.translator = QTranslator()
            if self.translator.load(localePath):
                QCoreApplication.installTranslator(self.translator)
            else:
                QgsMessageLog.logMessage("Translator was not installed.", "Loading Pugin") #Message to user

    def add_action(self, icon_path, text, callback, parent=None):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        self.toolbar.addAction(action)
        self.iface.addPluginToMenu(self.menu, action)
        self.actions.append(action)
        return action

    def initGui(self):
        icon_path = os.path.join(self.plugin_dir, 'icon.png')
        if not os.path.exists(icon_path):
            icon_path = ':/plugins/gmonitoring_networks/icon.png'

        self.add_action(
            icon_path,
            text="MonitoringNetworks",
            callback=self.run,
            parent=self.iface.mainWindow()
        )

    def unload(self):
        for action in self.actions:
            self.iface.removePluginMenu(self.menu, action)
            self.iface.removeToolBarIcon(action)
        del self.toolbar

    def run(self):
        # Crea una nueva instancia del diálogo cada vez que se ejecute el plugin.
        from .monitoring_networks_dialog import MonitoringNetworksDialog

        self.dlg = MonitoringNetworksDialog(self.iface)
        self.dlg.show()