# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MonitoringNetworksDialog
                                 A QGIS plugin
 Optimize the selection of monitoring wells to maximize information and mininize costs
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-14
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Lorena Gonzalez
        email                : lorenagzp@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

import gstools as gs
import numpy as np
from scipy import stats

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

STAT_KEYS = (
    'count', 'min', 'max', 'mean', 'median',
    'std', 'variance', 'asymmetry', 'kurtosis',
)

_ID_FIELD_HINTS = (
    'id', 'fid', 'clave', 'cve', 'pozo', 'well', 'name', 'nombre',
)

class MonitoringNetworksAnalysis:
    """Class for the analysis of the monitoring networks"""

    def __init__(self, parent=None):
        """Constructor."""
        #super(MonitoringNetworksAnalysis, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

def extract_coordinates_and_values_from_layer(layer, attribute):
    """
    Extracts coordinates and values from an attribute of a QGIS layer.

    Args:
        layer: QGIS QgsVectorLayer
        attribute: name of the attribute to extract

    Returns:
        tuple: (coordinates, values, null_count)
        - coordinates: array of coordinates (n_points, 2) with [x, y]
        - values: array of attribute values (n_points,)
        - null_count: number of null values found
        Returns (None, None, 0) if there is an error or no valid data
    """
    try:
        from qgis.core import QgsVectorLayer
        from PyQt5.QtCore import QVariant
        
        if not isinstance(layer, QgsVectorLayer):
            return None, None, 0
        
        field_index = layer.fields().indexOf(attribute)
        if field_index == -1:
            return None, None, 0
        
        coordinates = []
        values = []
        null_count = 0
        
        for feature in layer.getFeatures():
            geom = feature.geometry()
            if geom:
                point = geom.asPoint()
                value = feature[attribute]
                
                # Check if the value is NULL
                if value is None or (isinstance(value, QVariant) and value.isNull()):
                    null_count += 1
                else:
                    try:
                        float_value = float(value)
                        if not np.isnan(float_value) and not np.isinf(float_value):
                            coordinates.append([point.x(), point.y()])
                            values.append(float_value)
                        else:
                            null_count += 1
                    except (ValueError, TypeError):
                        null_count += 1
        
        if len(coordinates) == 0 or len(values) == 0:
            return None, None, null_count
        
        return np.array(coordinates), np.array(values), null_count
    
    except Exception:
        return None, None, 0


def apply_value_transform(values, transform='none'):
    """
    Applies a transformation to an array of values.

    Args:
        values: array-like of numeric values
        transform: 'none' or 'log'

    Returns:
        tuple: (transformed_values, excluded_non_positive, error_message)
        error_message is None on success; transformed_values is None on error
    """
    values = np.asarray(values, dtype=float)
    if transform in ('none', 0):
        return values, 0, None

    if transform in ('log', 1):
        positive_mask = values > 0
        excluded = int(np.sum(~positive_mask))
        positive_values = values[positive_mask]
        if positive_values.size == 0:
            return None, excluded, (
                "There are no positive values for the Log transformation."
            )
        return np.log(positive_values), excluded, None

    return values, 0, None


def align_coordinates_with_transform(coordinates, values, transform='none'):
    """
    Returns coordinates and values aligned after applying the same rules
    as apply_value_transform (e.g. log keeps only points with value > 0).

    Returns:
        tuple: (coordinates, transformed_values, excluded_non_positive, error_message)
    """
    coordinates = np.asarray(coordinates, dtype=float)
    values = np.asarray(values, dtype=float)
    transformed, excluded, error = apply_value_transform(values, transform)
    if error:
        return None, None, excluded, error
    if transform in ('none', 0):
        return coordinates, transformed, excluded, None
    positive_mask = values > 0
    return coordinates[positive_mask], transformed, excluded, None


def compute_descriptive_stats(values):
    """
    Computes descriptive statistics for a numeric array.

    Returns:
        dict with keys from STAT_KEYS, or None if there are no valid values
    """
    values = np.asarray(values, dtype=float)
    if values.size == 0:
        return None

    n = values.size
    result = {
        'count': n,
        'min': float(np.min(values)),
        'max': float(np.max(values)),
        'mean': float(np.mean(values)),
        'median': float(np.median(values)),
    }

    if n > 1:
        result['std'] = float(np.std(values, ddof=1))
        result['variance'] = float(np.var(values, ddof=1))
    else:
        result['std'] = float('nan')
        result['variance'] = float('nan')

    if n > 2:
        result['asymmetry'] = float(stats.skew(values, bias=False))
        result['kurtosis'] = float(stats.kurtosis(values, bias=False))
    else:
        result['asymmetry'] = float('nan')
        result['kurtosis'] = float('nan')

    return result


def resolve_point_id_field(layer, attribute):
    """
    Picks a layer field to use as point ID in cross-validation tables.

    Prefers common identifier field names; skips the analysis attribute.
    Returns None when no dedicated ID field is found (feature id is used).
    """
    from qgis.core import QgsVectorLayer

    if not isinstance(layer, QgsVectorLayer):
        return None

    attr_lower = attribute.lower()
    for field in layer.fields():
        name = field.name()
        if name.lower() == attr_lower:
            continue
        lower = name.lower()
        if lower in _ID_FIELD_HINTS or lower.endswith('id') or lower.endswith('cve'):
            return name
    return None


def extract_point_records_from_layer(layer, attribute, id_field=None):
    """
    Extracts point IDs, coordinates and values from a layer attribute.

    Returns:
        tuple: (point_ids, coordinates, values, null_count)
        point_ids are strings (from id_field or QGIS feature id).
    """
    try:
        from qgis.core import QgsVectorLayer
        from PyQt5.QtCore import QVariant

        if not isinstance(layer, QgsVectorLayer):
            return None, None, None, 0

        field_index = layer.fields().indexOf(attribute)
        if field_index == -1:
            return None, None, None, 0

        if id_field is None:
            id_field = resolve_point_id_field(layer, attribute)
        id_index = layer.fields().indexOf(id_field) if id_field else -1

        point_ids = []
        coordinates = []
        values = []
        null_count = 0

        for feature in layer.getFeatures():
            geom = feature.geometry()
            if not geom:
                continue

            point = geom.asPoint()
            value = feature[attribute]

            if value is None or (isinstance(value, QVariant) and value.isNull()):
                null_count += 1
                continue

            try:
                float_value = float(value)
                if np.isnan(float_value) or np.isinf(float_value):
                    null_count += 1
                    continue
            except (ValueError, TypeError):
                null_count += 1
                continue

            if id_index >= 0:
                raw_id = feature[id_field]
                if raw_id is None or (
                    isinstance(raw_id, QVariant) and raw_id.isNull()
                ):
                    point_id = str(feature.id())
                else:
                    point_id = str(raw_id)
            else:
                point_id = str(feature.id())

            point_ids.append(point_id)
            coordinates.append([point.x(), point.y()])
            values.append(float_value)

        if not point_ids:
            return None, None, None, null_count

        return (
            np.array(point_ids, dtype=object),
            np.array(coordinates),
            np.array(values),
            null_count,
        )
    except Exception:
        return None, None, None, 0


def align_point_ids_with_transform(point_ids, raw_values, transform='none'):
    """Keeps point IDs aligned with align_coordinates_with_transform filtering."""
    point_ids = np.asarray(point_ids, dtype=object)
    raw_values = np.asarray(raw_values, dtype=float)
    if transform in ('none', 0):
        return point_ids
    return point_ids[raw_values > 0]


def build_covariance_model(model_type, nugget, sill, range_val):
    """Builds a gstools covariance model from fitted variogram parameters."""
    nugget = max(float(nugget), 0.0)
    var = max(float(sill) - nugget, 1e-6)
    len_scale = max(float(range_val), 1e-6)

    if model_type == 'spherical':
        return gs.Spherical(dim=2, var=var, len_scale=len_scale, nugget=nugget)
    if model_type == 'exponential':
        return gs.Exponential(dim=2, var=var, len_scale=len_scale, nugget=nugget)
    if model_type == 'gaussian':
        return gs.Gaussian(dim=2, var=var, len_scale=len_scale, nugget=nugget)
    if model_type == 'stable':
        return gs.Stable(dim=2, var=var, len_scale=len_scale, nugget=nugget)
    return gs.Matern(dim=2, var=var, len_scale=len_scale, nugget=nugget)


def run_leave_one_out_cross_validation(
    coordinates, values, model_type, nugget, sill, range_val
):
    """
    Leave-one-out ordinary kriging cross-validation.

    Returns:
        dict with keys summary (min/max/mean of measured values, MAE, MSE, RMSE)
        and rows (per-point measured, predicted, error, SE, standardized error).
        Returns None when there are fewer than three valid points.
    """
    coordinates = np.asarray(coordinates, dtype=float)
    values = np.asarray(values, dtype=float)
    n = values.size
    if n < 3:
        return None

    x = coordinates[:, 0]
    y = coordinates[:, 1]
    model = build_covariance_model(model_type, nugget, sill, range_val)

    predicted = np.full(n, np.nan)
    kriging_var = np.full(n, np.nan)

    for i in range(n):
        train_mask = np.ones(n, dtype=bool)
        train_mask[i] = False
        krige = gs.krige.Ordinary(
            model,
            cond_pos=(x[train_mask], y[train_mask]),
            cond_val=values[train_mask],
        )
        estimate, variance = krige(
            (np.array([x[i]]), np.array([y[i]])),
            return_var=True,
        )
        predicted[i] = float(np.asarray(estimate).ravel()[0])
        kriging_var[i] = max(float(np.asarray(variance).ravel()[0]), 0.0)

    errors = values - predicted
    se = np.sqrt(kriging_var)
    with np.errstate(divide='ignore', invalid='ignore'):
        standardized = np.where(se > 0, errors / se, np.nan)

    abs_errors = np.abs(errors)
    mse = float(np.mean(errors ** 2))

    summary = {
        'min': float(np.min(values)),
        'max': float(np.max(values)),
        'mean': float(np.mean(values)),
        'mae': float(np.mean(abs_errors)),
        'mse': mse,
        'rmse': float(np.sqrt(mse)),
    }

    rows = []
    for i in range(n):
        rows.append({
            'measured': float(values[i]),
            'predicted': float(predicted[i]),
            'error': float(errors[i]),
            'se': float(se[i]),
            'standardized_error': float(standardized[i]),
        })

    return {'summary': summary, 'rows': rows}


def _mean_simple_kriging_variance(cond_coords, cond_vals, grid_coords, model, mean):
    """Mean simple-kriging variance over a set of grid nodes."""
    grid_coords = np.asarray(grid_coords, dtype=float)
    if cond_coords is None or len(np.asarray(cond_vals).ravel()) == 0:
        return float(model.var + model.nugget)

    cond_coords = np.asarray(cond_coords, dtype=float)
    cond_vals = np.asarray(cond_vals, dtype=float).ravel()
    gx = grid_coords[:, 0]
    gy = grid_coords[:, 1]
    cx = cond_coords[:, 0]
    cy = cond_coords[:, 1]

    krige = gs.krige.Simple(
        model,
        cond_pos=(cx, cy),
        cond_val=cond_vals,
        mean=float(mean),
    )
    _, variance = krige((gx, gy), return_var=True)
    variance = np.asarray(variance, dtype=float).ravel()
    return float(np.mean(variance))


def compute_simple_kriging_variance_reduction_curve(
    well_coordinates,
    well_values,
    grid_coordinates,
    model_type,
    nugget,
    sill,
    range_val,
    max_grid_nodes=500,
):
    """
    Greedy simple-kriging variance reduction curve for network optimization.

    Wells are added one at a time: at each step the remaining well that yields
    the lowest mean simple-kriging variance on the estimation grid is selected.

    Returns:
        dict with n_points, mean_variance, variance_reduction (%), selection_order;
        None when there are fewer than two wells or grid nodes.
    """
    well_coordinates = np.asarray(well_coordinates, dtype=float)
    well_values = np.asarray(well_values, dtype=float).ravel()
    grid_coordinates = np.asarray(grid_coordinates, dtype=float)
    n_wells = well_coordinates.shape[0]

    if n_wells < 2 or grid_coordinates.shape[0] < 1:
        return None

    if grid_coordinates.shape[0] > max_grid_nodes:
        rng = np.random.default_rng(0)
        pick = rng.choice(
            grid_coordinates.shape[0], size=max_grid_nodes, replace=False
        )
        grid_coordinates = grid_coordinates[pick]

    model = build_covariance_model(model_type, nugget, sill, range_val)
    sk_mean = float(np.mean(well_values))
    prior_variance = float(model.var + model.nugget)

    available = list(range(n_wells))
    selected = []
    n_points = [0]
    mean_variances = [prior_variance]
    selection_order = []

    while available:
        best_idx = None
        best_variance = np.inf
        for idx in available:
            trial_idx = selected + [idx]
            trial_coords = well_coordinates[trial_idx]
            trial_vals = well_values[trial_idx]
            trial_var = _mean_simple_kriging_variance(
                trial_coords, trial_vals, grid_coordinates, model, sk_mean
            )
            if trial_var < best_variance:
                best_variance = trial_var
                best_idx = idx

        selected.append(best_idx)
        available.remove(best_idx)
        selection_order.append(best_idx)
        n_points.append(len(selected))
        mean_variances.append(best_variance)

    mean_variances = np.asarray(mean_variances, dtype=float)
    if prior_variance > 0:
        variance_reduction = (1.0 - mean_variances / prior_variance) * 100.0
    else:
        variance_reduction = np.zeros_like(mean_variances)

    return {
        'n_points': np.asarray(n_points, dtype=int),
        'mean_variance': mean_variances,
        'variance_reduction': variance_reduction,
        'selection_order': np.asarray(selection_order, dtype=int),
        'prior_variance': prior_variance,
        'sk_mean': sk_mean,
        'grid_nodes_used': int(grid_coordinates.shape[0]),
    }