# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MonitoringNetworksDialog
                                 A QGIS plugin
 Optimize the selection of monitoring wells to maximize information and mininize costs
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-14
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Lorena Gonzalez
        email                : lorenagzp@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from dataclasses import dataclass
from typing import List, Optional

import gstools as gs
import numpy as np
from scipy import stats
from scipy.spatial.distance import cdist

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.core import QgsMessageLog

STAT_KEYS = (
    'count', 'min', 'max', 'mean', 'median',
    'std', 'variance', 'asymmetry', 'kurtosis',
)

_ID_FIELD_HINTS = (
    'id', 'clave', 'cve', 'pozo', 'well', 'name', 'nombre',
)

_WELL_WEIGHT_FIELD_HINTS = (
    'peso_pozo', 'well_weight', 'w_pozo', 'peso_w', 'well_w',
    'weight_well', 'pozo_peso','w'
)


@dataclass
class ParameterInput:
    """
    One geostatistical parameter measured at the monitoring wells.

    Each parameter has its own sample values, variogram model and optional
    user weight (tab 2). Spatial locations are shared at OptimizationInput level.
    """

    name: str
    values: np.ndarray
    model_type: str = 'spherical'
    nugget: float = 0.0
    sill: float = 0.0
    range_val: float = 0.0
    weight: float = 1.0


@dataclass
class OptimizationInput:
    """
    Full input for well-network variance-reduction optimization.

    Network-wide fields (coordinates, IDs, well/grid weights, estimation grid)
    are stored once. Each entry in ``parameters`` supplies values and a
    variogram for one contaminant or property.

    ``grid_coordinates`` must contain every estimation node from tab 3 (generated
    or imported). Kalman optimization uses the full grid, matching
    geostat_app_kalman_v10.
    """

    coordinates: np.ndarray
    grid_coordinates: np.ndarray
    parameters: List[ParameterInput]
    point_ids: Optional[np.ndarray] = None
    well_weights: Optional[np.ndarray] = None
    grid_weights: Optional[np.ndarray] = None

    def __post_init__(self):
        self.coordinates = np.asarray(self.coordinates, dtype=float)
        self.grid_coordinates = np.asarray(self.grid_coordinates, dtype=float)
        if not self.parameters:
            raise ValueError("At least one ParameterInput is required.")
        n_wells = self.coordinates.shape[0]
        for param in self.parameters:
            values = np.asarray(param.values, dtype=float).ravel()
            if values.size != n_wells:
                raise ValueError(
                    f"Parameter «{param.name}» has {values.size} values "
                    f"but {n_wells} well coordinates were provided."
                )


class MonitoringNetworksAnalysis:
    """Class for the analysis of the monitoring networks"""

    def __init__(self, parent=None):
        """Constructor."""
        #super(MonitoringNetworksAnalysis, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

def extract_coordinates_and_values_from_layer(layer, attribute):
    """
    Extracts coordinates and values from an attribute of a QGIS layer.

    Args:
        layer: QGIS QgsVectorLayer
        attribute: name of the attribute to extract

    Returns:
        tuple: (coordinates, values, null_count)
        - coordinates: array of coordinates (n_points, 2) with [x, y]
        - values: array of attribute values (n_points,)
        - null_count: number of null values found
        Returns (None, None, 0) if there is an error or no valid data
    """
    try:
        from qgis.core import QgsVectorLayer
        from PyQt5.QtCore import QVariant
        
        if not isinstance(layer, QgsVectorLayer):
            return None, None, 0
        
        field_index = layer.fields().indexOf(attribute)
        if field_index == -1:
            return None, None, 0
        
        coordinates = []
        values = []
        null_count = 0
        
        for feature in layer.getFeatures():
            geom = feature.geometry()
            if geom:
                point = geom.asPoint()
                value = feature[attribute]
                
                # Check if the value is NULL
                if value is None or (isinstance(value, QVariant) and value.isNull()):
                    null_count += 1
                else:
                    try:
                        float_value = float(value)
                        if not np.isnan(float_value) and not np.isinf(float_value):
                            coordinates.append([point.x(), point.y()])
                            values.append(float_value)
                        else:
                            null_count += 1
                    except (ValueError, TypeError):
                        null_count += 1
        
        if len(coordinates) == 0 or len(values) == 0:
            return None, None, null_count
        
        return np.array(coordinates), np.array(values), null_count
    
    except Exception:
        return None, None, 0


def extract_layer_coordinates(layer, include_fids=None):
    """
    Extracts XY coordinates from every point feature in a vector layer.

    Args:
        layer: QgsVectorLayer with point geometries.
        include_fids: optional set of feature IDs to keep; None keeps all.

    Returns:
        ndarray of shape (n_points, 2), or None when the layer is invalid
        or contains no point geometries.
    """
    try:
        from qgis.core import QgsVectorLayer

        if not isinstance(layer, QgsVectorLayer):
            return None

        coordinates = []
        for feature in layer.getFeatures():
            if include_fids is not None and feature.id() not in include_fids:
                continue
            geom = feature.geometry()
            if not geom or geom.isEmpty():
                continue
            point = geom.asPoint()
            coordinates.append([point.x(), point.y()])

        if not coordinates:
            return None
        return np.asarray(coordinates, dtype=float)
    except Exception:
        return None


def apply_value_transform(values, transform='none'):
    """
    Applies a transformation to an array of values.

    Args:
        values: array-like of numeric values
        transform: 'none' or 'log'

    Returns:
        tuple: (transformed_values, excluded_non_positive, error_message)
        error_message is None on success; transformed_values is None on error
    """
    values = np.asarray(values, dtype=float)
    if transform in ('none', 0):
        return values, 0, None

    if transform in ('log', 1):
        positive_mask = values > 0
        excluded = int(np.sum(~positive_mask))
        positive_values = values[positive_mask]
        if positive_values.size == 0:
            return None, excluded, (
                "There are no positive values for the Log transformation."
            )
        return np.log(positive_values), excluded, None

    return values, 0, None


def align_coordinates_with_transform(coordinates, values, transform='none'):
    """
    Returns coordinates and values aligned after applying the same rules
    as apply_value_transform (e.g. log keeps only points with value > 0).

    Returns:
        tuple: (coordinates, transformed_values, excluded_non_positive, error_message)
    """
    coordinates = np.asarray(coordinates, dtype=float)
    values = np.asarray(values, dtype=float)
    transformed, excluded, error = apply_value_transform(values, transform)
    if error:
        return None, None, excluded, error
    if transform in ('none', 0):
        return coordinates, transformed, excluded, None
    positive_mask = values > 0
    return coordinates[positive_mask], transformed, excluded, None


def compute_descriptive_stats(values):
    """
    Computes descriptive statistics for a numeric array.

    Returns:
        dict with keys from STAT_KEYS, or None if there are no valid values
    """
    values = np.asarray(values, dtype=float)
    if values.size == 0:
        return None

    n = values.size
    result = {
        'count': n,
        'min': float(np.min(values)),
        'max': float(np.max(values)),
        'mean': float(np.mean(values)),
        'median': float(np.median(values)),
    }

    if n > 1:
        result['std'] = float(np.std(values, ddof=1))
        result['variance'] = float(np.var(values, ddof=1))
    else:
        result['std'] = float('nan')
        result['variance'] = float('nan')

    if n > 2:
        result['asymmetry'] = float(stats.skew(values, bias=False))
        result['kurtosis'] = float(stats.kurtosis(values, bias=False))
    else:
        result['asymmetry'] = float('nan')
        result['kurtosis'] = float('nan')

    return result


def resolve_point_id_field(layer, attribute):
    """
    Picks a layer field to use as point ID in cross-validation tables.

    Prefers common identifier field names; skips the analysis attribute.
    Returns None when no dedicated ID field is found (fid is used).
    """
    from qgis.core import QgsVectorLayer

    if not isinstance(layer, QgsVectorLayer):
        return None

    attr_lower = attribute.lower()
    for field in layer.fields():
        name = field.name() #Get the name of the attribute header
        QgsMessageLog.logMessage("Attribute header to evaluate as ID for the wells: " + field.name(), "ID Field") #Debugging

        #If the attribute header is the same as the attribute to evaluate as ID, skip it
        if name.lower() == attr_lower: 
            continue

        lower = name.lower() #Convert the name of the attribute header to lowercase
        if lower in _ID_FIELD_HINTS:# or lower.endswith('id') or lower.endswith('cve'):
            QgsMessageLog.logMessage("Attribute to be used as ID for the wells: " + name, "ID Field") #Debugging
            return name #Return the name of the attribute header to be used as ID for the wells
    QgsMessageLog.logMessage("No attribute header found to be used as ID for the wells, defaulting to fid", "ID Field") #Debugging
    return None #Return None if no attribute header is found to be used as ID for the wells (fid used instead)


def resolve_well_weight_field(layer, attribute):
    """
    Picks a layer field to use as per-well weight during prioritization.

    Matches common weight column names (same keywords as geostat_app_kalman_v10).
    Skips the analysis attribute and ID-like fields.
    """
    from qgis.core import QgsVectorLayer

    if not isinstance(layer, QgsVectorLayer):
        return None

    attr_lower = attribute.lower()
    for field in layer.fields():
        name = field.name()
        lower = name.lower().strip()
        if lower == attr_lower:
            continue
        if lower in _ID_FIELD_HINTS or lower.endswith('id') or lower.endswith('cve'):
            continue
        if lower in _WELL_WEIGHT_FIELD_HINTS:
            return name
    return None


def _sanitize_well_weights(weights):
    """Ensures well weights are positive (non-positive values are replaced)."""
    weights = np.asarray(weights, dtype=float)
    if weights.size == 0:
        return weights
    positive = weights[weights > 0]
    fallback = float(np.min(positive)) if positive.size > 0 else 1.0
    return np.where(weights > 0, weights, fallback)


def extract_point_records_from_layer(
    layer, attribute, id_field=None, weight_field=None, include_fids=None
):
    """
    Extracts point IDs, coordinates, values and optional well weights.

    Args:
        include_fids: optional set of feature IDs to keep; None keeps all.
            Unchecked wells on Tab 1 are excluded before null/value filtering.

    Returns:
        tuple: (point_ids, coordinates, values, null_count, well_weights)
        well_weights are 1.0 when no weight field is available.
    """
    try:
        from qgis.core import QgsVectorLayer
        from PyQt5.QtCore import QVariant

        if not isinstance(layer, QgsVectorLayer):
            return None, None, None, 0, None

        field_index = layer.fields().indexOf(attribute)
        if field_index == -1:
            return None, None, None, 0, None

        if id_field is None:
            id_field = resolve_point_id_field(layer, attribute)
        id_index = layer.fields().indexOf(id_field) if id_field else -1

        if weight_field is None:
            weight_field = resolve_well_weight_field(layer, attribute)
        weight_index = layer.fields().indexOf(weight_field) if weight_field else -1

        point_ids = []
        coordinates = []
        values = []
        well_weights = []
        null_count = 0

        for feature in layer.getFeatures():
            if include_fids is not None and feature.id() not in include_fids:
                continue

            geom = feature.geometry()
            if not geom:
                continue

            point = geom.asPoint()
            value = feature[attribute]

            if value is None or (isinstance(value, QVariant) and value.isNull()):
                null_count += 1
                continue

            try:
                float_value = float(value)
                if np.isnan(float_value) or np.isinf(float_value):
                    null_count += 1
                    continue
            except (ValueError, TypeError):
                null_count += 1
                continue

            if id_index >= 0:
                raw_id = feature[id_field]
                if raw_id is None or (
                    isinstance(raw_id, QVariant) and raw_id.isNull()
                ):
                    point_id = str(feature.id())
                else:
                    point_id = str(raw_id)
            else:
                point_id = str(feature.id())

            weight = 1.0
            if weight_index >= 0:
                raw_weight = feature[weight_field]
                if raw_weight is not None and not (
                    isinstance(raw_weight, QVariant) and raw_weight.isNull()
                ):
                    try:
                        weight = float(raw_weight)
                    except (ValueError, TypeError):
                        weight = 1.0

            point_ids.append(point_id)
            coordinates.append([point.x(), point.y()])
            values.append(float_value)
            well_weights.append(weight)

        if not point_ids:
            return None, None, None, null_count, None

        return (
            np.array(point_ids, dtype=object),
            np.array(coordinates),
            np.array(values),
            null_count,
            _sanitize_well_weights(np.array(well_weights)),
        )
    except Exception:
        return None, None, None, 0, None


def build_point_id_layer_attribute_map(layer, attribute, include_fids=None):
    """
    Map point ID strings to full layer attribute dicts for valid analysis points.

    Uses the same point-ID assignment and attribute validity rules as
    ``extract_point_records_from_layer`` so export rows align with optimization.

    Args:
        include_fids: optional set of feature IDs to keep; None keeps all.

    Returns:
        tuple: (field_names, records_by_point_id)
            field_names: layer field names in QgsFields order.
            records_by_point_id: dict mapping point_id str -> {field: raw value}.
        Returns ([], {}) when the layer or attribute is invalid.
    """
    try:
        from qgis.core import QgsVectorLayer
        from PyQt5.QtCore import QVariant

        if not isinstance(layer, QgsVectorLayer):
            return [], {}

        fields = layer.fields()
        field_names = [field.name() for field in fields]
        if not field_names:
            return [], {}

        field_index = fields.indexOf(attribute)
        if field_index == -1:
            return [], {}

        id_field = resolve_point_id_field(layer, attribute)
        id_index = fields.indexOf(id_field) if id_field else -1

        records_by_point_id = {}
        for feature in layer.getFeatures():
            if include_fids is not None and feature.id() not in include_fids:
                continue
            if not feature.geometry():
                continue

            value = feature[attribute]
            if value is None or (isinstance(value, QVariant) and value.isNull()):
                continue

            try:
                float_value = float(value)
                if np.isnan(float_value) or np.isinf(float_value):
                    continue
            except (ValueError, TypeError):
                continue

            if id_index >= 0:
                raw_id = feature[id_field]
                if raw_id is None or (
                    isinstance(raw_id, QVariant) and raw_id.isNull()
                ):
                    point_id = str(feature.id())
                else:
                    point_id = str(raw_id)
            else:
                point_id = str(feature.id())

            records_by_point_id[point_id] = {
                name: feature[name] for name in field_names
            }

        return field_names, records_by_point_id
    except Exception:
        return [], {}


def align_point_ids_with_transform(point_ids, raw_values, transform='none'):
    """Keeps point IDs aligned with align_coordinates_with_transform filtering."""
    point_ids = np.asarray(point_ids, dtype=object)
    raw_values = np.asarray(raw_values, dtype=float)
    if transform in ('none', 0):
        return point_ids
    return point_ids[raw_values > 0]


def align_well_weights_with_transform(well_weights, raw_values, transform='none'):
    """Keeps well weights aligned with align_coordinates_with_transform filtering."""
    well_weights = np.asarray(well_weights, dtype=float)
    raw_values = np.asarray(raw_values, dtype=float)
    if transform in ('none', 0):
        return well_weights
    return well_weights[raw_values > 0]


def build_covariance_model(model_type, nugget, sill, range_val):
    """Builds a gstools covariance model from fitted variogram parameters."""
    nugget = max(float(nugget), 0.0)
    var = max(float(sill) - nugget, 1e-6)
    len_scale = max(float(range_val), 1e-6)

    if model_type == 'spherical':
        return gs.Spherical(dim=2, var=var, len_scale=len_scale, nugget=nugget)
    if model_type == 'exponential':
        return gs.Exponential(dim=2, var=var, len_scale=len_scale, nugget=nugget)
    if model_type == 'gaussian':
        return gs.Gaussian(dim=2, var=var, len_scale=len_scale, nugget=nugget)
    if model_type == 'stable':
        return gs.Stable(dim=2, var=var, len_scale=len_scale, nugget=nugget)
    return gs.Matern(dim=2, var=var, len_scale=len_scale, nugget=nugget)


# Number of lag-bin edges for experimental variogram (shared by fit and plot).
VARIOGRAM_N_BINS = 15


def compute_variogram_lag_r2(bin_center, gamma, model):
    """
    Coefficient of determination for experimental vs model variogram at lag bins.

    Uses the same bins shown on the Tab 2 plot:

        γ_hat(h) = model.variogram(bin_center)
        SS_res = Σ (γ_exp − γ_hat)²
        SS_tot = Σ (γ_exp − mean(γ_exp))²
        R² = 1 − SS_res / SS_tot

    This UI metric replaces gstools ``fit_variogram(..., return_r2=True)`` so
    reported R² tracks visual lag-bin alignment after auto-fit and manual edits.

    Returns:
        float R², or 0.0 when bins are insufficient or SS_tot is ~0.
    """
    bin_center = np.asarray(bin_center, dtype=float).ravel()
    gamma = np.asarray(gamma, dtype=float).ravel()
    if bin_center.size < 2 or gamma.size != bin_center.size or model is None:
        return 0.0

    try:
        gamma_hat = np.asarray(model.variogram(bin_center), dtype=float).ravel()
    except Exception:
        return 0.0

    if gamma_hat.size != gamma.size:
        return 0.0

    valid = np.isfinite(gamma) & np.isfinite(gamma_hat)
    if np.sum(valid) < 2:
        return 0.0

    y = gamma[valid]
    y_hat = gamma_hat[valid]
    ss_res = float(np.sum((y - y_hat) ** 2))
    ss_tot = float(np.sum((y - np.mean(y)) ** 2))
    if ss_tot <= 1e-15:
        return 0.0
    return float(1.0 - ss_res / ss_tot)


def compute_cross_validation_summary(errors):
    """
    Builds cross-validation summary metrics from prediction errors.

    The first three statistics are min, max and mean of the signed error
    (measured - predicted). MAE, MSE and RMSE use only finite error values.

    Returns:
        dict with keys min, max, mean, mae, mse, rmse.
    """
    errors = np.asarray(errors, dtype=float).ravel()
    valid_errors = errors[np.isfinite(errors)]
    if valid_errors.size == 0:
        return {
            'min': np.nan,
            'max': np.nan,
            'mean': np.nan,
            'mae': np.nan,
            'mse': np.nan,
            'rmse': np.nan,
        }

    abs_errors = np.abs(valid_errors)
    mse = float(np.mean(valid_errors ** 2))
    return {
        'min': float(np.min(valid_errors)),
        'max': float(np.max(valid_errors)),
        'mean': float(np.mean(valid_errors)),
        'mae': float(np.mean(abs_errors)),
        'mse': mse,
        'rmse': float(np.sqrt(mse)),
    }


def run_ordinary_kriging_cross_validation(
    coordinates,
    values,
    model_type,
    nugget,
    sill,
    range_val,
    network_indices=None,
):
    """
    Ordinary-kriging cross-validation for a full dataset or a monitoring network.

    When network_indices is None, every point is in the network and each point
    is predicted with leave-one-out among all points (standard LOO CV).

    When network_indices is provided, network wells are cross-validated with
    leave-one-out among the network; other wells are predicted using the full
    network as conditioning data only.

    Returns:
        dict with summary (error min/max/mean, MAE, MSE, RMSE) and rows
        (measured, predicted, error, SE, standardized error, included).
        None when there are fewer than three points or fewer than three
        successful predictions.
    """
    coordinates = np.asarray(coordinates, dtype=float)
    values = np.asarray(values, dtype=float)
    n = values.size
    if n < 3:
        return None

    if network_indices is None:
        network_mask = np.ones(n, dtype=bool)
    else:
        network_indices = np.asarray(network_indices, dtype=int)
        if network_indices.size < 1:
            return None
        network_mask = np.zeros(n, dtype=bool)
        network_mask[network_indices] = True

    x = coordinates[:, 0]
    y = coordinates[:, 1]
    model = build_covariance_model(model_type, nugget, sill, range_val)

    predicted = np.full(n, np.nan)
    kriging_var = np.full(n, np.nan)
    included_flags = np.zeros(n, dtype=bool)

    for i in range(n):
        if network_mask[i]:
            train_mask = network_mask.copy()
            train_mask[i] = False
            if np.sum(train_mask) < 1:
                continue
            included_flags[i] = True
        else:
            train_mask = network_mask
            if np.sum(train_mask) < 1:
                continue

        krige = gs.krige.Ordinary(
            model,
            cond_pos=(x[train_mask], y[train_mask]),
            cond_val=values[train_mask],
        )
        estimate, variance = krige(
            (np.array([x[i]]), np.array([y[i]])),
            return_var=True,
        )
        predicted[i] = float(np.asarray(estimate).ravel()[0])
        kriging_var[i] = max(float(np.asarray(variance).ravel()[0]), 0.0)

    if np.sum(np.isfinite(predicted)) < 3:
        return None

    errors = predicted - values # predicted - measureds
    se = np.sqrt(kriging_var)
    with np.errstate(divide='ignore', invalid='ignore'):
        standardized = np.where(se > 0, errors / se, np.nan)

    if network_indices is not None:
        summary_errors = errors[included_flags]
    else:
        summary_errors = errors

    summary = compute_cross_validation_summary(summary_errors)

    rows = []
    for i in range(n):
        rows.append({
            'included': bool(included_flags[i]),
            'measured': float(values[i]),
            'predicted': float(predicted[i]),
            'error': float(errors[i]),
            'se': float(se[i]),
            'standardized_error': float(standardized[i]),
        })

    return {'summary': summary, 'rows': rows}


def normalized_grid_weights(grid_weights):
    """
    Normalizes grid node weights for weighted variance aggregation.

    Same convention as geostat_app_kalman_v10: pesos_norm = pesos * n / sum(pesos).
    """
    weights = _sanitize_well_weights(np.asarray(grid_weights, dtype=float).ravel())
    if weights.size == 0:
        return None
    return weights * weights.size / np.sum(weights)


def _mean_simple_kriging_variance(cond_coords, cond_vals, grid_coords, model, grid_weights=None):
    """
    Normalized sum of ordinary-kriging variances on the estimation grid.

    Same metric as calcular_varianza_kriging in geostat_app_kalman_v10 (phase 2),
    without grid or well weights.
    """
    grid_coords = np.asarray(grid_coords, dtype=float)
    cond_vals = np.asarray(cond_vals, dtype=float).ravel()
    if cond_coords is None or cond_vals.size == 0:
        return np.inf

    cond_coords = np.asarray(cond_coords, dtype=float)
    gx = grid_coords[:, 0]
    gy = grid_coords[:, 1]
    cx = cond_coords[:, 0]
    cy = cond_coords[:, 1]

    partial_sill = float(model.var)
    nugget_value = float(model.nugget)
    sill_total = partial_sill + nugget_value
    norm_factor = sill_total if sill_total > 0 else 1.0

    krige = gs.krige.Ordinary(
        model,
        cond_pos=(cx, cy),
        cond_val=cond_vals,
    )
    krige((gx, gy))
    krige_var = np.asarray(krige.krige_var, dtype=float).ravel()

    if grid_weights is not None:
        grid_weights = np.asarray(grid_weights, dtype=float).ravel()
        if grid_weights.size == krige_var.size:
            pesos_norm = normalized_grid_weights(grid_weights)
            return float(np.dot(krige_var, pesos_norm) / norm_factor / 2.0)

    return float(np.sum(krige_var) / norm_factor / 2.0)


def _init_kalman_covariance_state(well_coordinates, grid_coordinates, model):
    """Builds Kalman covariance state for one variogram model."""
    n_grid = grid_coordinates.shape[0]
    partial_sill = float(model.var)
    R = max(float(model.nugget), 1e-6)

    dist_gc = cdist(grid_coordinates, well_coordinates)
    C_gc = model.covariance(dist_gc).astype(np.float64)
    dist_cc = cdist(well_coordinates, well_coordinates)
    C_cc = model.covariance(dist_cc).astype(np.float64)
    var_grid = np.full(n_grid, partial_sill, dtype=np.float64)

    return {
        'var_grid': var_grid,
        'C_gc': C_gc,
        'C_cc': C_cc,
        'R': R,
    }


def _kalman_candidate_reduction(k, state, pesos_norm):
    """Grid variance reduction for assimilating candidate well k (phase 1 score)."""
    c_gk = state['C_gc'][:, k]
    sigma_kk = state['C_cc'][k, k]
    S = sigma_kk + state['R']
    if S <= 1e-12:
        return 0.0
    reduccion_por_nodo = (c_gk ** 2) / S
    if pesos_norm is not None:
        return float(np.dot(reduccion_por_nodo, pesos_norm))
    return float(np.sum(reduccion_por_nodo))


def _kalman_rank1_update(k, state):
    """Rank-1 Kalman covariance update after selecting well k."""
    c_gk = state['C_gc'][:, k].copy()
    c_ck = state['C_cc'][:, k].copy()
    sigma_kk = state['C_cc'][k, k]
    S = sigma_kk + state['R']
    if S <= 1e-12:
        return
    inv_S = 1.0 / S
    state['var_grid'] -= (c_gk ** 2) * inv_S
    np.maximum(state['var_grid'], 0.0, out=state['var_grid'])
    state['C_gc'] -= np.outer(c_gk, c_ck) * inv_S
    state['C_cc'] -= np.outer(c_ck, c_ck) * inv_S


def compute_total_variance_percent(normalized_variances):
    """
    Remaining total variance on a 0–100% scale relative to the no-wells baseline.

    100% means no variance reduction (zero wells in the network).
    0% means full reduction (theoretical limit; not reached in practice).

    Args:
        normalized_variances: Sequence indexed by optimization step; index 0 is
            the baseline with no wells (same units as phase-2 OK aggregate).

    Returns:
        1-D float array, same length as ``normalized_variances``.
    """
    varianzas = np.asarray(normalized_variances, dtype=float).ravel()
    if varianzas.size == 0:
        return varianzas
    var_initial = float(varianzas[0])
    if var_initial > 0.0:
        return 100.0 * varianzas / var_initial
    return np.full(varianzas.shape, 100.0, dtype=float)


def wells_at_fraction_of_max_reduction(results, fraction=0.9):
    """
    Smallest well count where prioritized variance reduction reaches a fraction
    of the maximum achievable reduction (same threshold as the Tab 4 90% line).

    Uses ``variance_reduction`` and ``n_points`` from
    ``compute_variance_reduction_curve`` (priority / Kalman order).

    Args:
        results: Optimize results dict (must include variance_reduction, n_points).
        fraction: Target share of max reduction in (0, 1], e.g. 0.9 for 90%.

    Returns:
        int well count, or None when the curve is missing or empty.
    """
    if not results:
        return None

    reduction = np.asarray(results.get('variance_reduction', []), dtype=float)
    n_points = np.asarray(results.get('n_points', []), dtype=int)
    if reduction.size < 2 or n_points.size != reduction.size:
        return None

    max_reduction = float(reduction[-1])
    # No measurable reduction: fall back to the full network size.
    if max_reduction <= 0.0:
        return int(n_points[-1])

    target = float(fraction) * max_reduction
    # Index 0 is the zero-well baseline; search from the first selected well.
    for i in range(1, reduction.size):
        if reduction[i] >= target:
            return int(n_points[i])
    return int(n_points[-1])


def _greedy_kalman_selection_order(
    param_states,
    param_weights,
    pesos_norm,
    well_weights,
    mode='max',
    progress_callback=None,
    progress_start=0.05,
    progress_end=0.50,
    progress_message='selecting',
):
    """
    Phase-1 greedy well ordering from Kalman candidate scores.

    score(k) = well_weight[k] * sum_p(w_p * reduction_p(k))

    Args:
        mode: ``'max'`` picks largest score first (priority order).
            ``'min'`` picks smallest score first (adverse order).
        progress_callback: Optional ``callable(fraction, message, **kwargs)``.
        progress_start / progress_end: Fraction range for this phase.

    Tie-break: when scores are equal, the first candidate in the current
    ``disponibles`` iteration order wins (stable, same as the original
    max-greedy loop that used strict ``>`` / ``<`` comparisons).

    Returns:
        List of well indices in selection order.
    """
    n_candidates = param_states[0]['C_cc'].shape[0] if param_states else 0
    selected = []
    disponibles = list(range(n_candidates))
    minimize = mode == 'min'

    for step in range(len(disponibles)):
        best_idx = None
        best_score = np.inf if minimize else -np.inf

        for k in disponibles:
            combined_reduction = 0.0
            for weight, state in zip(param_weights, param_states):
                combined_reduction += weight * _kalman_candidate_reduction(
                    k, state, pesos_norm
                )
            well_factor = well_weights[k] if well_weights is not None else 1.0
            score = well_factor * combined_reduction
            # Strict inequality keeps the first equal score (tie-break).
            if minimize:
                if score < best_score:
                    best_score = score
                    best_idx = k
            elif score > best_score:
                best_score = score
                best_idx = k

        # Same residual threshold as the original max-greedy: once no
        # meaningful reduction remains, append leftover wells as-is.
        if best_idx is not None and best_score > 1e-15:
            for state in param_states:
                _kalman_rank1_update(best_idx, state)
            selected.append(best_idx)
            disponibles.remove(best_idx)
        else:
            selected.extend(disponibles)
            break

        if progress_callback is not None and n_candidates > 0:
            fraction = progress_start + (
                (progress_end - progress_start) * (step + 1) / n_candidates
            )
            progress_callback(
                fraction,
                progress_message,
                current=step + 1,
                total=n_candidates,
            )

    return selected


def _ok_variance_curve_along_order(
    selected,
    well_coordinates,
    grid_coordinates,
    parameters,
    param_models,
    param_weights,
    grid_weights,
    n_grid,
    progress_callback=None,
    progress_start=0.50,
    progress_end=1.0,
    progress_message='evaluating',
):
    """
    Phase-2 OK total-variance curve along a fixed well order.

    Returns:
        dict with n_points, normalized_variances, variance_reduction,
        total_variance_percent.
    """
    num_puntos = [0]
    varianzas = [float(n_grid)]
    indices_acumulados = []
    n_selected = len(selected)

    for step, idx in enumerate(selected):
        indices_acumulados.append(idx)
        sel_coords = well_coordinates[indices_acumulados]
        step_vars = []
        for param, model in zip(parameters, param_models):
            sel_vals = np.asarray(param.values, dtype=float)[indices_acumulados]
            var_ok = _mean_simple_kriging_variance(
                sel_coords,
                sel_vals,
                grid_coordinates,
                model,
                grid_weights=grid_weights,
            )
            step_vars.append(var_ok)
        varianzas.append(float(np.dot(param_weights, step_vars)))
        num_puntos.append(len(indices_acumulados))

        if progress_callback is not None and n_selected > 0:
            fraction = progress_start + (
                (progress_end - progress_start) * (step + 1) / n_selected
            )
            progress_callback(
                fraction,
                progress_message,
                current=step + 1,
                total=n_selected,
            )

    varianzas = np.asarray(varianzas, dtype=float)
    num_puntos = np.asarray(num_puntos, dtype=int)
    var_inicial = varianzas[0]
    if var_inicial > 0:
        variance_reduction = (1.0 - varianzas / var_inicial) * 100.0
    else:
        variance_reduction = np.zeros_like(varianzas)

    return {
        'n_points': num_puntos,
        'normalized_variances': varianzas,
        'variance_reduction': variance_reduction,
        'total_variance_percent': compute_total_variance_percent(varianzas),
    }


def compute_variance_reduction_curve(optimization_input, progress_callback=None):
    """
    Greedy Kalman well prioritization with an ordinary-kriging variance curve.

    Uses the full estimation grid supplied in ``OptimizationInput`` (every node
    generated on tab 3 or imported from Excel). This matches geostat_app_kalman_v10,
    which evaluates the full ``df_malla`` without random subsampling.

    Accepts one or several parameters via ``OptimizationInput``. When multiple
    parameters are supplied, each keeps its own variogram (no cross-covariance);
    phase 1 ranks wells by a weighted sum of per-parameter grid variance
    reductions, and phase 2 combines per-parameter OK variances with the same
    weights.

    Phase 1 — well ordering (fast Kalman / SK-equivalent covariance updates):
        score(k) = well_weight[k] * sum_p( w_p * reduction_p(k) )
        where reduction_p(k) is the weighted grid variance drop if well k is
        assimilated for parameter p, and w_p are tab-2 weights (normalized).
        Priority order uses max score; adverse order uses min score (least
        reduction first) on a fresh covariance state.

    Phase 2 — variance-reduction curve along each selected order:
        At step t, V(t) = sum_p( w_p * OK_variance_p(t) )
        Baseline V(0) = n_grid nodes (geostat_app_kalman_v10 convention).

    Args:
        optimization_input: Wells, grid, parameters and optional weights.
        progress_callback: Optional ``callable(fraction, message, **kwargs)``
            invoked during phase 1 and phase 2. ``fraction`` is in [0, 1].
            ``message`` identifies the phase (e.g. ``"selecting"``).

    Returns:
        dict with priority curve keys (n_points, normalized_variances,
        variance_reduction, total_variance_percent, selection_order) plus
        adverse_* counterparts, grid_node_count, combined_mode, parameters,
        parameter_weights; or None if inputs are insufficient.
    """
    def emit_progress(fraction, message="", **kwargs):
        if progress_callback is not None:
            progress_callback(fraction, message, **kwargs)

    if not isinstance(optimization_input, OptimizationInput):
        return None

    try:
        well_coordinates = np.asarray(optimization_input.coordinates, dtype=float)
        parameters = optimization_input.parameters
    except (ValueError, TypeError):
        return None

    n_candidates = well_coordinates.shape[0]
    if n_candidates < 1:
        return None

    grid_coordinates = np.asarray(optimization_input.grid_coordinates, dtype=float)
    grid_weights = optimization_input.grid_weights
    well_weights = optimization_input.well_weights

    n_grid = grid_coordinates.shape[0]
    if n_grid < 1:
        return None

    if well_weights is not None:
        well_weights = np.asarray(well_weights, dtype=float).ravel()
        if well_weights.size != n_candidates:
            well_weights = None

    pesos_norm = None
    if grid_weights is not None:
        grid_weights = np.asarray(grid_weights, dtype=float).ravel()
        if grid_weights.size != n_grid:
            grid_weights = None
        else:
            # Normalize spatial priorities on the estimation grid (tab 3 / tab 4).
            pesos_norm = normalized_grid_weights(grid_weights)

    raw_weights = np.asarray(
        [max(float(param.weight), 0.0) for param in parameters],
        dtype=float,
    )
    if np.sum(raw_weights) <= 0:
        param_weights = np.full(len(parameters), 1.0 / len(parameters))
    else:
        param_weights = raw_weights / np.sum(raw_weights)

    # One Kalman covariance state per parameter (same wells, different variograms).
    param_models = []
    for param in parameters:
        param_models.append(
            build_covariance_model(
                param.model_type,
                param.nugget,
                param.sill,
                param.range_val,
            )
        )

    def fresh_param_states():
        return [
            _init_kalman_covariance_state(
                well_coordinates, grid_coordinates, model
            )
            for model in param_models
        ]

    emit_progress(0.05, "preparing")

    # Phase 1a: priority order (largest variance reduction first).
    selected = _greedy_kalman_selection_order(
        fresh_param_states(),
        param_weights,
        pesos_norm,
        well_weights,
        mode='max',
        progress_callback=emit_progress,
        progress_start=0.05,
        progress_end=0.275,
        progress_message='selecting',
    )

    # Phase 1b: adverse order (smallest variance reduction first).
    adverse_selected = _greedy_kalman_selection_order(
        fresh_param_states(),
        param_weights,
        pesos_norm,
        well_weights,
        mode='min',
        progress_callback=emit_progress,
        progress_start=0.275,
        progress_end=0.50,
        progress_message='selecting_adverse',
    )

    # Phase 2: OK variance curves along both fixed orders.
    priority_curve = _ok_variance_curve_along_order(
        selected,
        well_coordinates,
        grid_coordinates,
        parameters,
        param_models,
        param_weights,
        grid_weights,
        n_grid,
        progress_callback=emit_progress,
        progress_start=0.50,
        progress_end=0.75,
        progress_message='evaluating',
    )
    adverse_curve = _ok_variance_curve_along_order(
        adverse_selected,
        well_coordinates,
        grid_coordinates,
        parameters,
        param_models,
        param_weights,
        grid_weights,
        n_grid,
        progress_callback=emit_progress,
        progress_start=0.75,
        progress_end=1.0,
        progress_message='evaluating_adverse',
    )

    combined_mode = len(parameters) > 1
    emit_progress(1.0, "complete")
    return {
        'n_points': priority_curve['n_points'],
        'normalized_variances': priority_curve['normalized_variances'],
        'variance_reduction': priority_curve['variance_reduction'],
        'total_variance_percent': priority_curve['total_variance_percent'],
        'selection_order': np.asarray(selected, dtype=int),
        'adverse_n_points': adverse_curve['n_points'],
        'adverse_normalized_variances': adverse_curve['normalized_variances'],
        'adverse_variance_reduction': adverse_curve['variance_reduction'],
        'adverse_total_variance_percent': adverse_curve['total_variance_percent'],
        'adverse_selection_order': np.asarray(adverse_selected, dtype=int),
        'grid_node_count': int(n_grid),
        'combined_mode': combined_mode,
        'parameters': [param.name for param in parameters],
        'parameter_weights': {
            param.name: float(weight)
            for param, weight in zip(parameters, param_weights)
        },
    }


def ordinary_kriging_interpolation(
    well_coordinates,
    well_values,
    grid_coordinates,
    model_type,
    nugget,
    sill,
    range_val,
    return_std_error=False,
):
    """
    Ordinary-kriging estimates at grid nodes using the fitted variogram model.

    Args:
        return_std_error: When True, also return kriging standard error at each
            grid node: ``sqrt(max(kriging_variance, 0))`` from gstools
            ``return_var=True`` (same source as leave-one-out CV SE).

    Returns:
        If ``return_std_error`` is False: 1-D estimates array, or None on failure.
        If True: ``(estimates, std_error)``, or ``(None, None)`` on failure.
    """
    def _fail():
        return (None, None) if return_std_error else None

    well_coordinates = np.asarray(well_coordinates, dtype=float)
    well_values = np.asarray(well_values, dtype=float).ravel()
    grid_coordinates = np.asarray(grid_coordinates, dtype=float)

    if well_values.size < 1 or grid_coordinates.shape[0] < 1:
        return _fail()

    model = build_covariance_model(model_type, nugget, sill, range_val)
    cx = well_coordinates[:, 0]
    cy = well_coordinates[:, 1]
    gx = grid_coordinates[:, 0]
    gy = grid_coordinates[:, 1]

    krige = gs.krige.Ordinary(
        model,
        cond_pos=(cx, cy),
        cond_val=well_values,
    )
    n_grid = grid_coordinates.shape[0]

    # Request kriging variance when SE is needed; otherwise keep the lighter call.
    if return_std_error:
        result = krige((gx, gy), return_var=True)
        if isinstance(result, tuple) and len(result) >= 2:
            estimates = np.asarray(result[0], dtype=float)
            kriging_var = np.asarray(result[1], dtype=float)
        else:
            estimates = np.asarray(result, dtype=float)
            kriging_var = (
                np.asarray(krige.krige_var, dtype=float)
                if hasattr(krige, 'krige_var') and krige.krige_var is not None
                else None
            )
    else:
        result = krige((gx, gy))
        kriging_var = None
        if hasattr(krige, 'field') and krige.field is not None:
            estimates = np.asarray(krige.field, dtype=float)
        elif isinstance(result, tuple):
            estimates = np.asarray(result[0], dtype=float)
        else:
            estimates = np.asarray(result, dtype=float)

    estimates = np.asarray(estimates, dtype=float).ravel()
    if estimates.size != n_grid and estimates.size > n_grid:
        # Avoid duplicated values when gstools returns stacked outputs
        estimates = estimates[:n_grid]

    if estimates.size != n_grid:
        return _fail()

    if not return_std_error:
        return estimates

    if kriging_var is None:
        return _fail()

    kriging_var = np.asarray(kriging_var, dtype=float).ravel()
    if kriging_var.size != n_grid and kriging_var.size > n_grid:
        kriging_var = kriging_var[:n_grid]
    if kriging_var.size != n_grid:
        return _fail()

    # Standard error is the square root of (non-negative) kriging variance.
    std_error = np.sqrt(np.maximum(kriging_var, 0.0))
    return estimates, std_error


def _excel_cell_value(value):
    """
    Coerces a Python/numpy value to a type XlsxWriter can write to a cell.

    Empty cells are written as None. Non-finite floats become blank cells so
    Excel does not show NaN/Inf literals.
    """
    if value is None:
        return None
    if isinstance(value, (np.floating, float)):
        value = float(value)
        return None if np.isnan(value) or np.isinf(value) else value
    if isinstance(value, (np.integer, int)):
        return int(value)
    if isinstance(value, (np.bool_, bool)):
        return bool(value)
    return value


def _sanitize_excel_sheet_name(sheet_name):
    """
    Returns an Excel-safe worksheet title (max 31 chars, no forbidden chars).

    XlsxWriter rejects names containing : \\ / ? * [ ] or exceeding 31 chars.
    """
    invalid_chars = str.maketrans({
        ':': '_',
        '\\': '_',
        '/': '_',
        '?': '_',
        '*': '_',
        '[': '_',
        ']': '_',
    })
    safe = str(sheet_name).translate(invalid_chars).strip()
    if not safe:
        safe = "Sheet"
    return safe[:31]


def write_excel_sheets(file_path, sheet_specs):
    """
    Write a multi-sheet .xlsx file using XlsxWriter (export path only).

    Exports use XlsxWriter instead of openpyxl because several QGIS builds on
    Windows crash with an access violation inside openpyxl when initializing
    workbook styles (NamedStyle copy / libxml2). XlsxWriter writes data-only
    workbooks without that style bootstrap.

    Grid import continues to use openpyxl read-only mode in
    ``read_excel_table_rows`` because XlsxWriter is write-only.

    Args:
        file_path: Destination .xlsx path.
        sheet_specs: Iterable of (sheet_name, column_names, row_dicts).
            Each row_dict maps column name -> cell value.
    """
    try:
        import xlsxwriter
    except ImportError as exc:
        raise ImportError(
            "xlsxwriter is required to export Excel files."
        ) from exc

    if not sheet_specs:
        raise ValueError("At least one worksheet specification is required.")

    output_path = str(file_path)
    workbook = xlsxwriter.Workbook(
        output_path,
        {
            # Keep well IDs and similar fields as text unless explicitly numeric.
            'strings_to_numbers': False,
        },
    )
    try:
        for sheet_name, columns, rows in sheet_specs:
            if not columns:
                continue
            worksheet = workbook.add_worksheet(
                _sanitize_excel_sheet_name(sheet_name)
            )
            for col_idx, column in enumerate(columns):
                worksheet.write(0, col_idx, str(column))
            for row_idx, row in enumerate(rows, start=1):
                for col_idx, column in enumerate(columns):
                    worksheet.write(
                        row_idx,
                        col_idx,
                        _excel_cell_value(row.get(column)),
                    )
    finally:
        # Always close so partial files are flushed or the handle is released.
        workbook.close()


def read_excel_table_rows(file_path):
    """
    Read the first worksheet as a list of row tuples (openpyxl read-only).

    Import uses openpyxl because XlsxWriter is write-only. Read-only mode avoids
    the style initialization path that crashes during export on some systems.

    Returns:
        list[tuple]: all rows including the header row, if present.
    """
    try:
        from openpyxl import load_workbook
    except ImportError as exc:
        raise ImportError("openpyxl is required to read Excel files.") from exc

    wb = load_workbook(file_path, read_only=True, data_only=True)
    try:
        ws = wb.active
        return list(ws.iter_rows(values_only=True))
    finally:
        wb.close()